services:
  devopsquickscan.api:
    container_name: devopsquickscan.api
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5000
    restart: always
