@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for the DevOps Quickscan Software System

Person(facilitator, "Facilitator", "The person who leads the DevOps Quick Scan session")
Person(participant, "Participant", "The person who participates in the DevOps Quick Scan session")

Container(webapp, "Blazor Web App", "Blazor, .NET, SignalR", "Provides all the internet banking functionality to customers via their web browser.")
System_Ext(files, "Azure Blob Storage", "Stores all question and session information in json files.")

Container_Boundary(webapp_container, "Web Application") {
    Component(startSession, "Start Session Page", "Razor Page", "Allows facilitators to start a new session.")
    Component(joinSession, "Join Session Page", "Razor Page", "Allows participants to join a session.")
    Component(facilitatorSession, "Facilitator Session Page", "Razor Page", "Allows facilitators to manage the session, ask questions, reveal answers, end the session.")
    Component(participantSession, "Participant Session Page", "Razor Page", "Shows the participants the questions to answer, and the collected answers.")
    Component(qrcodePage, "QR Code Page", "Razor Page", "Shows a QR code, so participants can join by scanning the QR code with a mobile device.")

    Component(sessionService, "SessionService", ".NET Service", "Manages the session state and the participants.")

    Component(sessionRepository, "SessionRepository", ".NET Service", "Handles the storage and retrieval of session data.")
    Component(questionRepository, "QuestionRepository", ".NET Service", "Handles the storage and retrieval of question data.")
}

Rel(facilitator, webapp, "Leads the DevOps Quick Scan session")
Rel(participant, webapp, "Participates in the DevOps Quick Scan session")

Rel(webapp, startSession, "Uses", "JSON/HTTPS")
Rel(webapp, joinSession, "Uses", "HTTPS")
Rel(webapp, facilitatorSession, "Uses", "HTTPS/SIGNALR")
Rel(webapp, participantSession, "Uses", "HTTPS/SIGNALR")
Rel(webapp, qrcodePage, "Uses", "HTTPS/SIGNALR")

Rel(startSession, sessionService, "Uses", "JSON/HTTPS")
Rel(joinSession, sessionService, "Uses", "JSON/HTTPS")
Rel(facilitatorSession, sessionService, "Uses", "JSON/HTTPS")
Rel(participantSession, sessionService, "Uses", "JSON/HTTPS")
Rel(qrcodePage, sessionService, "Uses", "JSON/HTTPS")

Rel(sessionService, sessionRepository, "Uses", "JSON/HTTPS")
Rel(sessionService, questionRepository, "Uses", "JSON/HTTPS")
Rel(sessionRepository, files, "Uses", "JSON/HTTPS")
Rel(questionRepository, files, "Uses", "JSON/HTTPS")

@enduml