@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title System Context for the DevOpsQuickScan Application

Person(facilitator, "Facilitator", "The person who leads the DevOps Quick Scan session")
Person(participant, "Participant", "The person who participates in the DevOps Quick Scan session")

System_Boundary(s1, "DevOpsQuickScan") {
    System(devopsquickscan, "Wep Application", "A web application for managing sessions and participants of the DevOps Quick Scan")
}

Rel(facilitator, devopsquickscan, "Leads the DevOps Quick Scan session")
Rel(participant, devopsquickscan, "Participates in the DevOps Quick Scan session")

@enduml