@startuml
start

:Facilitator starts session;
:Facilitator invites participants;

partition Participants {
  :Login;
  :Wait for questions;
}

repeat

    partition Facilitator {
    :Choose a question;
    :Request answers;
    }

    partition Participants {
    :Answer question;
    :Wait for results;
    }

    :Facilitator reveals answers;
    :Discuss answers;

repeat while (More questions?)

stop
@enduml