@startuml

title Application States

scale 600 width

[*] --> NotStarted
NotStarted --> QuestionPending: Facilitator started a new session,\nparticipants can join
NotStarted: Facilitator can start a new session
QuestionPending: Facilitator goes through questions to select the next question
QuestionPending --> CollectingAnswers 
CollectingAnswers: Facilitator selected a question,\nparticipants can answer
CollectingAnswers --> RevealingAnswers
RevealingAnswers: Participants can see all answers,\ndiscuss the oucome
RevealingAnswers --> QuestionPending: Facilitator can select a new question
RevealingAnswers --> SessionEnded
SessionEnded --> [*]: Session ended
SessionEnded: Facilitator can download results

@enduml
